[package]

name = "proc_world"
version = "0.0.1"
authors = ["Ulysse Carion <ulysse@ulysse.io>"]

[dependencies.image]

git = "https://github.com/PistonDevelopers/image"

[dependencies.noise]

git = "https://github.com/bjz/noise-rs"
